sudo: false
dist: trusty
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install
  - polymer install

before_script:
  - gulp lint
  #- polymer lint --rules polymer-2 --input *.html

env:
  - TEST_SUITE=mobile
  - TEST_SUITE=polyfilled
  - TEST_SUITE=desktop

script:
  - if [[ "$TEST_SUITE" = "desktop" ]]; then
       xvfb-run -s '-screen 0 1024x768x24' polymer test
    fi
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
       xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs:$TEST_SUITE --expanded --verbose;
    fi
  # - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
  #     xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
  #   fi

after_success:
  # - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
