sudo: false
dist: trusty
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules
    - bower_components

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - polymer install

before_script:
  - gulp lint version:check
  #- polymer lint --rules polymer-2 --input *.html

env:
  - TEST_SUITE=mobile
  - TEST_SUITE=polyfilled
  - TEST_SUITE=desktop

script:
  - if [[ "$TEST_SUITE" = "desktop" ]]; then
      xvfb-run -s '-screen 0 1024x768x24' wct;
    fi
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
      xvfb-run -s '-screen 0 1024x768x24' wct --env saucelabs:$TEST_SUITE --expanded --verbose;
    fi
  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      if [[ "$TEST_SUITE" = "desktop" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' wct --env saucelabs-cron;
      fi;
    fi

after_success:
  # - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
