sudo: false
dist: trusty
language: node_js
node_js: stable

addons:
  google-chrome: latest

cache:
  directories:
    - node_modules

script:
  - gulp lint
  - travis_retry xvfb-run wct --local=chrome

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
