sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g bower
  - bower install
  - npm install -g web-component-tester
  - npm install -g coveralls@2.11.3
env:
  # desktop
  - BROWSER1="Windows 10/chrome@54"
    BROWSER2="Windows 10/firefox@50"
    BROWSER3="Windows 10/microsoftedge@13"
    BROWSER4="Windows 10/internet explorer@11"
    BROWSER5="OS X 10.11/safari@9.0"
  # mobile
  - BROWSER1="OS X 10.11/iphone@9.2"
    BROWSER2="OS X 10.11/ipad@9.2"
    BROWSER3="Linux/android@5.1"
    BROWSER4=" "
    BROWSER5=" "
script:
  - gulp lint:html
  - gulp lint:js
  - travis_retry wct --sauce="$BROWSER1" --sauce="$BROWSER2" --sauce="$BROWSER3" --sauce="$BROWSER4" --sauce="$BROWSER5"
  - travis_retry wct --sauce="$BROWSER1" --sauce="$BROWSER2" --sauce="$BROWSER3" --sauce="$BROWSER4" --sauce="$BROWSER5" test/shadow.html
after_success:
  - cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls
