name: local

on: [pull_request]

jobs:
  polymer-2:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install latest npm
      # magi-cli 1.0 requires npm 7 or higher
      run: "npm install -g npm@8"

    - name: Install global npm dependencies
      # bower is needed to run 'bower install'
      run: "npm install --quiet --no-progress --global bower"

    - name: Install project npm dependencies
      run: "npm ci"

    - name: Install project Bower dependencies
      run: "bower install --quiet"

    - name: Run automated magi-cli checks
      run: "npm run check"

    - name: Run a linter
      run: "npm run lint"

    - name: Run unit tests
      run: xvfb-run -s '-screen 0 1024x768x24' npm test

    - name: Run unit tests - Polymer2 specific
      run: xvfb-run -s '-screen 0 1024x768x24' npm test --suite polymer2Only

  polymer-3:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Check out the (Polymer 2) source code
      uses: actions/checkout@v2

    - name: Install latest npm
      # magi-cli 1.0 requires npm 7 or higher
      run: "npm install -g npm@8"

    - name: Install global npm dependencies
      # bower and polymer-modulizer are needed to run the Polymer 3 conversion step
      run: "npm install --quiet --no-progress --global bower magi-cli@next polymer-modulizer"

    - name: Convert the source code to Polymer 3
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        magi p3-convert --out . --import-style=name

    - name: Run unit tests
      run: xvfb-run -s '-screen 0 1024x768x24' npm test
