name: sauce-p3-mobile

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install CLI tools
      run: npm install -g bower magi-cli polymer-modulizer web-component-tester yarn

    - name: Install dependencies
      run: npm -q i

    - name: Convert to P3
      run: magi p3-convert --out . --import-style=name

    - name: Run yarn
      run: yarn install --flat

    - name: Run unit tests set 1
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:mobile

    - name: Run unit tests set 2
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:mobile test/column.html test/data-provider.html  test/drag-and-drop.html  test/dynamic-item-size.html  test/event-context.html  test/filtering.html  test/frozen-columns.html  test/hidden-grid.html  test/tree-toggle.html  test/iron-list.html  test/keyboard-navigation.html  test/lazy-import.html  test/light-dom-observing.html
    
    - name: Run unit tests set 3
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:mobile test/physical-count.html  test/resizing.html  test/resizing-material.html  test/row-details.html  test/row-height.html  test/scroll-to-index.html  test/scrolling-mode.html  test/selecting.html  test/sorting.html  test/style-scope.html  test/templates.html  test/renderers.html