name: sauce-p2

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install latest npm
      # magi-cli 1.0 requires npm 7 or higher
      run: "npm install -g npm@8"

    - name: Install global npm dependencies
      # bower is needed to run 'bower install'
      run: "npm install --quiet --no-progress --global bower"

    - name: Install project npm dependencies
      run: "npm ci"

    - name: Install project Bower dependencies
      run: "bower install --quiet"

    - name: Run unit tests [Desktop / Batch 1]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites batch1

    - name: Run unit tests [Desktop / Batch 2]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites batch2

    - name: Run unit tests [Desktop / Batch 3]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites batch3

    - name: Run unit tests [Desktop / Batch 4]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites batch4

    - name: Run unit tests [Desktop / Batch 5]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites batch5

    - name: Run unit tests [Desktop / Polymer2 Only]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs:desktop --suites polymer2Only
