name: sauce-p2

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install global npm dependencies
      # bower is needed to run 'bower install'
      run: "npm install --quiet --no-progress --global bower"

    - name: Install project npm dependencies
      run: "npm ci"

    - name: Install project Bower dependencies
      run: "bower install --quiet"

      # workaround for running tests on Android on SauceLabs (see wct.conf.js)
    - name: Add 'localhost-for-saucelabs' to /etc/hosts
      run: echo "127.0.0.1 localhost-for-saucelabs" | sudo tee -a /etc/hosts

    - name: Run unit tests [Desktop / Batch 1]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites batch1

    - name: Run unit tests [Desktop / Batch 2]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites batch2

    - name: Run unit tests [Desktop / Batch 3]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites batch3

    - name: Run unit tests [Desktop / Batch 4]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites batch4

    - name: Run unit tests [Desktop / Batch 5]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites batch5

    - name: Run unit tests [Desktop / Polymer2 Only]
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm test -- --env saucelabs --suites polymer2Only
